services:
  pcapng-analyzer:
    build: .
    container_name: pcapng_analyzer
    network_mode: host 
    volumes:
      - /var/log/alerts:/var/log 
    environment:
      - DB_HOST=127.0.0.1 
      - LEARNING_MODE=True
      - SNIFFER_INTERFACE=ens3
      - DB_PORT=5432
      - DB_NAME=sniffer_db
      - DB_USER=sniffer_admin
      - DB_PASSWORD_FILE=/run/secrets/db_password
    depends_on:
      sniffer-db:
        condition: service_healthy
    secrets:
      - db_password
    restart: always

  sniffer-db:
    image: postgres:15-alpine
    container_name: sniffer_db
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: sniffer_db
      POSTGRES_USER: sniffer_admin
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sniffer_internal
    secrets:
      - db_password
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sniffer_admin -d sniffer_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-backup:
    image: jkaninda/pg-bkup:latest
    container_name: db_backup
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        export DB_PASSWORD=$$(cat /run/secrets/db_password)
        export GPG_PASSPHRASE=$$(cat /run/secrets/gpg_passphrase)
        exec pg-bkup backup -d sniffer_db --cron-expression '@every 1h'
    environment:
      DB_HOST: sniffer-db
      DB_PORT: 5432
      DB_USERNAME: sniffer_admin
      BACKUP_RETENTION_DAYS: 7
    volumes:
      - ./db_backups:/backup
    depends_on:
      sniffer-db:
        condition: service_healthy
    networks:
      - sniffer_internal
    secrets:
      - db_password
      - gpg_passphrase
    restart: always

secrets:
  db_password:
    file: ./db_password.txt
  gpg_passphrase:
    file: ./gpg_passphrase.txt 

    
volumes:
  postgres_data: 

networks:
  sniffer_internal: